# Defined via `source`
function lock --wraps=env\ \'XSECURELOCK_SHOW_HOSTNAME=0\'\ \'XSECURELOCK_PASSWORD_PROMPT=asterisks\'\ \'XSECURELOCK_AUTH_BACKGROUND_COLOR=\#282828\'\ \'XSECURELOCK_AUTH_FOREGROUND_COLOR=\#fcf1c7\'\ \'XSECURE_DIM_COLOR=\#282828\'\ xsecurelock --description alias\ lock=env\ \'XSECURELOCK_SHOW_HOSTNAME=0\'\ \'XSECURELOCK_PASSWORD_PROMPT=asterisks\'\ \'XSECURELOCK_AUTH_BACKGROUND_COLOR=\#282828\'\ \'XSECURELOCK_AUTH_FOREGROUND_COLOR=\#fcf1c7\'\ \'XSECURE_DIM_COLOR=\#282828\'\ xsecurelock
  env 'XSECURELOCK_SHOW_HOSTNAME=0' 'XSECURELOCK_PASSWORD_PROMPT=asterisks' 'XSECURELOCK_AUTH_BACKGROUND_COLOR=#282828' 'XSECURELOCK_AUTH_FOREGROUND_COLOR=#fcf1c7' 'XSECURE_DIM_COLOR=#282828' xsecurelock $argv; 
end
